### PR TITLE
Add support for image loading with CocoaPods 0.36 and frameworks

### PR DESCRIPTION
**Pull request by TwinkyDaniel**
Hi there,

I am using your library in my hobby app for some time now and I am very happy with it. Unfortunately I found an issue with using it in CocoaPods 0.36. The image loading mechanism fails. Details are here:

 http://blog.cocoapods.org/CocoaPods-0.36

This pull request fixes that issue.

Thanks for your work ;-)

### CODE REVIEW

**Comment by problame** [comment]
I cannot reproduce a crash or failing `pod install/update` commands.
Please provide more details / an example project showcasing your particular problem.

General information:
`CSNotificationView` generates the *CSNotificationView bundle* through CocoaPods.

```
# CSNotificationView.podspec
s.resource_bundle = { 'CSNotificationView' => ['CSNotificationView/Resources/*.png'] }
```

**Comment by TwinkyDaniel** [comment]
I am using the new CocoaPods 0.36 together with swift that is using frameworks internally. The crash does not happen during pod install/update but at app runtime. In my case I was calling [CSNotificationView dismissWithStyle:message:duration:animated] which called [CSNotificationView imageForStyle:]. And the crash happens inside that method. [NSBundle mainBundle] returns nil because the resource loading mechanism did change with the latest CocoaPod version. This is described at http://blog.cocoapods.org/CocoaPods-0.36 (scroll down to Caveats).

For reference, this is my podfile:

```
use_frameworks!
pod 'CSNotificationView'
```

**Comment by problame** [comment]
Thanks for your contribution.

**Comment by problame** [comment]
Update has been pushed. Thanks again!

**Pull request closed without merging**
